version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ai_notifications
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api-gateway:
    build: ../apps/api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - collector-service
      - aggregator-service
      - ai-summarizer
      - notifier-service

  auth-service:
    build: ../services/auth-service
    ports:
      - "4001:4001"